#!/usr/bin/env python3
"""
Generate wakewordlab/_loader/key.c from the WAKEWORDLAB_PUBLIC_KEY env var.
Run by CI before the Cython extension is compiled.

Usage:
    WAKEWORDLAB_PUBLIC_KEY=9f3e7c... python scripts/gen_key.py
"""

import os
import sys
from pathlib import Path

OUT = Path(__file__).parent.parent / "wakewordlab/_loader/key.c"

TEMPLATE = """\
/*
 * key.c - generated by CI, do not commit.
 * _K_A[i] ^ _K_B[i] == PUBLIC_KEY[i]
 */
#include <stdint.h>
#include <string.h>

static const uint8_t _K_A[32] = {{
{a_rows}
}};

static const uint8_t _K_B[32] = {{
{b_rows}
}};

void wkw_get_public_key(uint8_t *out) {{
    int i;
    for (i = 0; i < 32; i++) {{
        out[i] = _K_A[i] ^ _K_B[i];
    }}
}}
"""


def _fmt_rows(data: bytes) -> str:
    rows = []
    for i in range(0, 32, 8):
        chunk = data[i : i + 8]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(rows)


def main() -> None:
    key_hex = os.environ.get("WAKEWORDLAB_PUBLIC_KEY", "").strip()
    if len(key_hex) != 64:
        sys.exit(
            "ERROR: WAKEWORDLAB_PUBLIC_KEY env var must be exactly 64 hex chars.\n"
            "Set it as a GitHub Actions secret."
        )

    key = bytes.fromhex(key_hex)
    mask = os.urandom(32)
    a = bytes(k ^ m for k, m in zip(key, mask))
    b = mask

    OUT.write_text(
        TEMPLATE.format(a_rows=_fmt_rows(a), b_rows=_fmt_rows(b))
    )
    print(f"Generated {OUT}")


if __name__ == "__main__":
    main()
